-Manually merged from rm_branch because I was getting this error when I tried to merge using GIT:
/cygdrive/d/GDrive/Documents/QII/University/Laurier/CP670AndroidProgramming/Project/rm_branch
$ git checkout master
error: Your local changes to the following files would be overwritten by checkout:
        .idea/gradle.xml
        app/src/androidTest/java/com/example/cp670_project/MealTest.java
        app/src/main/java/com/example/cp670_project/Account.java
        app/src/main/java/com/example/cp670_project/AddExerciseFragment.java
        app/src/main/java/com/example/cp670_project/AddMealFragment.java
        app/src/main/java/com/example/cp670_project/DashBoardFragment.java
        app/src/main/java/com/example/cp670_project/ExercisesDataSource.java
        app/src/main/java/com/example/cp670_project/Meal.java
        app/src/main/java/com/example/cp670_project/MySQLiteOpenHelper.java
        app/src/main/res/drawable-hdpi/dumbell_bench_press.png
        app/src/main/res/drawable-mdpi/dumbell_bench_press.png
        app/src/main/res/drawable-xhdpi/dumbell_bench_press.png
        app/src/main/res/drawable-xxhdpi/dumbell_bench_press.png
        app/src/main/res/drawable-xxxhdpi/dumbell_bench_press.png
Please commit your changes or stash them before you switch branches.
Aborting